/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115067-gdf868bae23-20240504"
#endif /* AVUTIL_FFVERSION_H */
